[package]
name = "render-2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
lodepng = "3.4.6"
winit = "0.25.0"
ecs-core = {path="../ecs-core"}